#%RAML 1.0
title: Blah

/resource:
  get:
    body:
      application/xml:
        type: !include https://raw.githubusercontent.com/dreamflyer/testRepo/master/endpoints/schemas/scheme.xsd
        example:  |
          <country><country_name>France</country_name>
          <population>59.7</population></country>
